### ISSUE TITLE
New/DLC weapons

### ISSUE THREAD

**Issue by whyyn0tt** [fredford/cod_camo_tracker#1]
Love this tool, would like to see the newer weapons added.

**Comment by fredford** [comment]
Can do! I didn't know anyone else actually used the app, so if I do anything that messes up your tracker progress my apologies!

**Comment by fredford** [comment]
@whyyn0tt I added as many of the new weapons to the game as I could see. Let me know if I missed any from Vanguard.

If you press the "UPDATE" button it should update your data without losing any of your progress.

There is one issue I noticed that I will be checking out, is that with all of the new weapons you don't need to complete all of them to get Atomic. So I'll be adding another check for that while reworking the app a bit.

Thanks!!
